export const IntroRoute = [
    "/intro/guru-pronam",
    "/intro/gita-great-life",
    "/intro/manual-of-life",
    "/intro/clarity-of-lfe",
    "/intro/puspose-and-important",
    "/intro/gita-dyanam",
    "/intro/gita-fact",
    "/intro/gita-love-message",
    "/intro/chapters-1-to-6",
    "/intro/chapters-7-to-12",
    "/intro/chapters-13-to-18",
    "/intro/journey-within",
    "/intro/back-to-godhead",
    "/intro/conclusion",
]

export const OneRoute = [
    "/one/mahabharat",
    "/one/mahabharat-map",
    "/one/sloka-1",
    "/one/1-translate",
    "/one/lesson-1",
    "/one/1-2",
    "/one/2-3",
    "/one/4-11",
    "/one/lesson-2",
    "/one/sloka-12",
    "/one/lesson-3",
    '/intro/blew-conchshell',
]

const routes = [
    "/intro",
    "/intro/guru-pronam",
    "/intro/gita-great-life",
    "/intro/manual-of-life",
    "/intro/clarity-of-lfe",
    "/intro/puspose-and-important",
    "/intro/gita-dyanam",
    "/intro/gita-fact",
    "/intro/gita-love-message",
    "/intro/chapters-1-to-6",
    "/intro/chapters-7-to-12",
    "/intro/chapters-13-to-18",
    "/intro/journey-within",
    "/intro/back-to-godhead",
    "/intro/conclusion",

    "/one",
    "/one/mahabharat",
    "/one/mahabharat-map",
    "/one/sloka-1",
    "/one/1-translate",
    "/one/lesson-1",
    "/one/1-2",
    "/one/2-3",
    "/one/4-11",
    "/one/lesson-2",
    "/one/sloka-12",
    "/one/lesson-3",
    '/intro/blew-conchshell',
]

export default routes